# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-name'],
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-name'],
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-name'],
                'verbose_name': 'Edition',
                'verbose_name_plural': 'Editions',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('negotiable', models.BooleanField()),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('OLD', 'Old')], max_length=1)),
                ('seller_type', models.CharField(choices=[('DEALER', 'Dealer'), ('PRIVATE', 'Private')], max_length=1)),
                ('fuel', models.CharField(choices=[('DIESEL', 'Diesel'), ('ELECTRO', 'Electro'), ('GASOLINE', 'Gasoline')], max_length=1)),
                ('transmission', models.CharField(choices=[('AUTOMATIC', 'Automatic'), ('MANUAL', 'Manual')], max_length=1)),
                ('lifestyle', models.CharField(choices=[('FAMILY', 'Family'), ('LUXURY', 'Luxury'), ('OFFROAD', 'Offroad'), ('CLASSIC', 'Classic')], max_length=1)),
                ('color_family', models.CharField(choices=[('WHITE', 'White'), ('BLACK', 'Black')], max_length=1)),
                ('details', models.TextField(blank=True, null=True)),
                ('submitted_on', models.DateField(verbose_name='Submitted on')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Brand', verbose_name='Brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Category', verbose_name='Category')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Edition', verbose_name='Brand')),
            ],
            options={
                'ordering': ['-submitted_on'],
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
    ]
