# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 15:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='negotiable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='submitted_on',
            field=models.DateField(default=datetime.datetime(2017, 2, 23, 15, 58, 42, 816692), verbose_name='Submitted on'),
        ),
    ]
