# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170223_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='submitted_on',
            field=models.DateField(auto_now=True, verbose_name='Submitted on'),
        ),
    ]
