# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170223_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color_family',
            field=models.CharField(choices=[('WHITE', 'White'), ('BLACK', 'Black')], max_length=1, verbose_name='Color Family'),
        ),
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.CharField(choices=[('NEW', 'New'), ('OLD', 'Old')], max_length=1, verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='item',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='item',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Edition', verbose_name='Edition'),
        ),
        migrations.AlterField(
            model_name='item',
            name='fuel',
            field=models.CharField(choices=[('DIESEL', 'Diesel'), ('ELECTRO', 'Electro'), ('GASOLINE', 'Gasoline')], max_length=1, verbose_name='Fuel'),
        ),
        migrations.AlterField(
            model_name='item',
            name='lifestyle',
            field=models.CharField(choices=[('FAMILY', 'Family'), ('LUXURY', 'Luxury'), ('OFFROAD', 'Offroad'), ('CLASSIC', 'Classic')], max_length=1, verbose_name='Lifestyle'),
        ),
        migrations.AlterField(
            model_name='item',
            name='seller_type',
            field=models.CharField(choices=[('DEALER', 'Dealer'), ('PRIVATE', 'Private')], max_length=1, verbose_name='Seller Type'),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='transmission',
            field=models.CharField(choices=[('AUTOMATIC', 'Automatic'), ('MANUAL', 'Manual')], max_length=1, verbose_name='Transmission'),
        ),
    ]
