# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170223_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('CAR', 'Car'), ('MOTORCYCLE', 'MotorCycle'), ('VEHICLE', 'Vehicle')], max_length=50, primary_key=True, serialize=False, verbose_name='Name'),
        ),
    ]
