# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-name'],
                'verbose_name': 'Brand',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(choices=[('CAR', 'Car'), ('MOTORCYCLE', 'MotorCycle'), ('VEHICLE', 'Vehicle')], max_length=50, primary_key=True, serialize=False, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-name'],
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-name'],
                'verbose_name': 'Edition',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='Name')),
                ('price', models.IntegerField(default=0)),
                ('negotiable', models.BooleanField(default=True)),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('OLD', 'Old')], max_length=50, verbose_name='Condition')),
                ('seller_type', models.CharField(choices=[('DEALER', 'Dealer'), ('PRIVATE', 'Private')], max_length=50, verbose_name='Seller Type')),
                ('fuel', models.CharField(choices=[('DIESEL', 'Diesel'), ('ELECTRO', 'Electro'), ('GASOLINE', 'Gasoline')], max_length=50, verbose_name='Fuel')),
                ('transmission', models.CharField(choices=[('AUTOMATIC', 'Automatic'), ('MANUAL', 'Manual')], max_length=50, verbose_name='Transmission')),
                ('lifestyle', models.CharField(choices=[('FAMILY', 'Family'), ('LUXURY', 'Luxury'), ('OFFROAD', 'Offroad'), ('CLASSIC', 'Classic')], max_length=50, verbose_name='Lifestyle')),
                ('color_family', models.CharField(choices=[('WHITE', 'White'), ('BLACK', 'Black')], max_length=50, verbose_name='Color Family')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Details')),
                ('submitted_on', models.DateField(auto_now=True, verbose_name='Submitted on')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bike.Brand', verbose_name='Brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bike.Category', verbose_name='Category')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bike.Edition', verbose_name='Edition')),
            ],
            options={
                'ordering': ['-submitted_on'],
                'verbose_name': 'Item',
            },
        ),
    ]
