# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-04 00:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_by', models.CharField(max_length=50)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-name'],
                'verbose_name': 'Brand',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('sku', models.CharField(blank=True, max_length=100, null=True, verbose_name='SKU')),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('price', models.DecimalField(decimal_places=2, default='0.0', max_digits=10)),
                ('stock', models.IntegerField(help_text='Stock Quantity', null=True)),
                ('company', models.CharField(default='', max_length=50, verbose_name='Company')),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('OLD', 'Old')], max_length=50, verbose_name='Condition')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Details')),
                ('submitted_on', models.DateField(auto_now=True, verbose_name='Submitted on')),
                ('active', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bike.Brand', verbose_name='Brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bike.Category', verbose_name='Category')),
                ('locations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.City', verbose_name='Locations')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_on'],
                'db_table': 'bike',
                'verbose_name': 'Item',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bike.SubCategory', verbose_name='Sub Category'),
        ),
        migrations.AddField(
            model_name='brand',
            name='category',
            field=models.ManyToManyField(blank=True, to='bike.Category'),
        ),
    ]
