# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='negotiable',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50),
        ),
    ]
