# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-25 00:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0002_auto_20171024_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='sub_category',
        ),
    ]
