# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0002_auto_20170226_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('CAR', 'Car'), ('MOTORCYCLE', 'Motorcycles'), ('VEHICLE', 'Vehicle')], max_length=100, verbose_name='Category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
