# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-04 00:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0003_auto_20171004_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank='True', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='bike.Category'),
        ),
    ]
