# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-25 00:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0003_remove_category_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bike.Category', verbose_name='Categories'),
        ),
    ]
