# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 10:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0003_item_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='color_family',
        ),
        migrations.RemoveField(
            model_name='item',
            name='fuel',
        ),
        migrations.RemoveField(
            model_name='item',
            name='lifestyle',
        ),
        migrations.RemoveField(
            model_name='item',
            name='negotiable',
        ),
        migrations.RemoveField(
            model_name='item',
            name='seller_type',
        ),
        migrations.RemoveField(
            model_name='item',
            name='transmission',
        ),
    ]
