# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0005_auto_20170304_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
