# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0005_auto_20170324_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Car', 'Car'), ('Motorcycle', 'Motorcycle'), ('Vehicle', 'Vehicle')], max_length=100, verbose_name='Category'),
        ),
    ]
