# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-25 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0005_auto_20171025_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sub_category',
        ),
        migrations.AlterField(
            model_name='brand',
            name='category',
            field=models.ManyToManyField(to='bike.Category', verbose_name='Sub Category'),
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
