# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_auto_20170306_1409'),
        ('bike', '0006_auto_20170304_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.Country', verbose_name='Country')),
            ],
            options={
                'ordering': ['-name'],
                'db_table': 'item',
                'verbose_name': 'Region',
            },
        ),
    ]
