# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_region'),
        ('bike', '0007_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='country',
        ),
        migrations.AddField(
            model_name='item',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.Region'),
        ),
        migrations.AlterModelTable(
            name='item',
            table='bike',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
