# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0008_auto_20170306_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='region',
            new_name='locations',
        ),
    ]
