# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0009_auto_20170306_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='locations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.Region', verbose_name='Locations'),
        ),
    ]
