# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-27 00:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0009_remove_category_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ('name', 'id'),
                'verbose_name_plural': 'Sub Categories',
            },
        ),
        migrations.AlterField(
            model_name='brand',
            name='category',
            field=models.ManyToManyField(to='bike.Category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='category',
            name='sub_categories',
            field=models.ManyToManyField(to='bike.SubCategory', verbose_name='Sub Category'),
        ),
        migrations.AddField(
            model_name='item',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bike.SubCategory', verbose_name='Sub Category'),
        ),
    ]
