# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0010_auto_20170307_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Car', 'Car'), ('Motorcycle', 'Motorcycles'), ('Vehicle', 'Vehicle')], max_length=100, verbose_name='Category'),
        ),
    ]
