# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-08 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0010_auto_20171008_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='category',
            name='sub_category',
            field=models.ManyToManyField(blank=True, null=True, to='bike.SubCategory', verbose_name='Sub Category'),
        ),
    ]
