# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-09 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0011_auto_20171008_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sub_category',
            field=models.ManyToManyField(to='bike.SubCategory', verbose_name='Sub Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='sub_category',
            field=models.ManyToManyField(blank=True, to='bike.SubCategory', verbose_name='Sub Category'),
        ),
    ]
