# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-09 00:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0012_auto_20171009_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='condition',
        ),
    ]
