# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-29 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Post')),
            ],
            options={
                'verbose_name': 'Tag',
            },
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('date',), 'verbose_name': 'Comment'},
        ),
    ]
