# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-05 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikeuser',
            name='is_verified',
            field=models.CharField(blank=True, editable=False, help_text=b'User account verification code.', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='bikeuser',
            name='reset_code',
            field=models.CharField(blank=True, editable=False, help_text=b'Password reset code.', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='bikeuser',
            name='reset_code_expire',
            field=models.DateTimeField(blank=True, editable=False, help_text=b'Password reset code expire date.', max_length=512, null=True),
        ),
    ]
