# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170424_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikeuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
