# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170316_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikeuser',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
