# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-name'],
                'db_table': 'geo',
                'verbose_name': 'Citie',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='Name')),
            ],
            options={
                'ordering': ['-name'],
                'verbose_name': 'Countrie',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.Country', verbose_name='Country'),
        ),
    ]
