# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 00:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_auto_20170324_1431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['-name'], 'verbose_name': 'Citie'},
        ),
    ]
